### Exercise 1 — Create an Array

Create a NumPy array containing the numbers:

```text
10, 20, 30, 40, 50
```

Print the array.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
for a in arr:
    print(a)

10
20
30
40
50


### Exercise 2 — Array Properties

Create the following array:

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```

Print:

* Number of dimensions
* Shape
* Number of elements
* Data type

In [2]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Number of dimensions
print(arr.ndim)

# Shape of the array
print(arr.shape)

# Number of elements in the array
print(arr.size)

# Data type of the array elements
print(arr.dtype)


2
(2, 3)
6
int32


### Exercise 3 — Zeros and Ones

Create:

1. An array containing 10 zeros.
2. A `3 × 4` matrix containing ones.

Print both arrays.

In [3]:
arr_zeros = np.zeros(10)
arr_ones = np.ones((3, 4))
print(arr_zeros)
print(arr_ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Exercise 4 — Generate a Sequence

Generate all even numbers from `2` to `20` using `np.arange()`.

Expected result:

```text
[ 2  4  6  8 10 12 14 16 18 20]
```

In [4]:
arr = np.arange(2, 21, 1)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### Exercise 5 — Generate Evenly Spaced Values

Generate 11 evenly spaced numbers between `0` and `10` using `np.linspace()`.

Expected result:

```text
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
```

In [5]:
arr = np.linspace(0, 10, 11)
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


### Exercise 6 — Indexing

Given:

```python
arr = np.array([5, 10, 15, 20, 25, 30])
```

Print:

* The first element
* The last element
* The third element
* The second-to-last element

In [6]:
arr = np.array([5, 10, 15, 20, 25, 30])
print(f"The first element is: {arr[0]}")
print(f"The last element is: {arr[-1]}")
print(f"The third element is: {arr[2]}")
print(f"The second to last element is: {arr[-2]}")

The first element is: 5
The last element is: 30
The third element is: 15
The second to last element is: 25


### Exercise 7 — Slicing

Given:

```python
arr = np.arange(1, 11)
```

Use slicing to obtain:

```text
[3 4 5 6 7]
```

In [7]:
arr = np.arange(1, 11)
print(arr[2:7])

[3 4 5 6 7]


### Exercise 8 — Matrix Indexing

Given:

```python
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
```

Extract:

* `20`
* `60`
* `70`
* `90`

Then extract the second row.

In [8]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

l = [
    int(matrix[0][1]),
    int(matrix[1][2]),
    int(matrix[2][0]),
    int(matrix[2][2])
]

print(l)

[20, 60, 70, 90]


### Exercise 9 — Reshape an Array

Create an array containing numbers from `1` to `12`.

Reshape it into:

```text
3 × 4
```

Expected result:

```text
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

In [9]:
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 10 — Mathematical Operations

Given:

```python
arr = np.array([2, 4, 6, 8, 10])
```

Calculate:

* Square of every number
* Cube of every number
* Square root of every number
* Number multiplied by `5`

In [10]:
arr = np.array([2, 4, 6, 8, 10])
print("Square of the elements in the array: ")
print([int(x**2) for x in arr])
print("Cube of every number in the array: ")
print([int(x**3) for x in arr])
print("Square root of every number in the array: ")
print([float(np.round(np.sqrt(x), 2)) for x in arr])
print("Number multiplied by 5 in the array: ")
print([int(x*5) for x in arr])   


Square of the elements in the array: 
[4, 16, 36, 64, 100]
Cube of every number in the array: 
[8, 64, 216, 512, 1000]
Square root of every number in the array: 
[1.41, 2.0, 2.45, 2.83, 3.16]
Number multiplied by 5 in the array: 
[10, 20, 30, 40, 50]


### Exercise 11 — Statistics

Given the following test scores:

```python
scores = np.array([75, 82, 91, 68, 88, 95, 73, 84])
```

Calculate:

* Mean
* Median
* Minimum
* Maximum
* Standard deviation
* Variance

In [11]:
scores = np.array([75, 82, 91, 68, 88, 95, 73, 84])
print(f"Mean: {float(np.round(np.mean(scores), 2))}")
print(f"Median: {float(np.round(np.median(scores), 2))}")
print(f"Minimum: {int(np.min(scores))}")
print(f"Maximum: {int(np.max(scores))}")
print(f"Standard deviation: {np.round(np.std(scores), 2)}")
print(f"Variance: {np.round(np.var(scores), 2)}")


Mean: 82.0
Median: 83.0
Minimum: 68
Maximum: 95
Standard deviation: 8.77
Variance: 77.0


### Exercise 12 — Filtering

Given:

```python
arr = np.array([12, 5, 18, 3, 25, 7, 30, 10])
```

Use Boolean indexing to find:

1. Numbers greater than `15`
2. Numbers less than `10`
3. Numbers between `10` and `25`

In [12]:
arr = np.array([12, 5, 18, 3, 25, 7, 30, 10])
print(f"Number greater than 15: {arr[arr > 15]}")
print(f"Number less than 10: {arr[arr < 10]}")
print(f"Number between 10 and 25: {arr[(arr >= 10) & (arr <= 25)]}")

Number greater than 15: [18 25 30]
Number less than 10: [5 3 7]
Number between 10 and 25: [12 18 25 10]


### Exercise 13 — Replace Values With `np.where()`

Given:

```python
scores = np.array([45, 72, 88, 39, 95, 60])
```

Use `np.where()` to replace:

* Scores greater than or equal to `50` → `"Pass"`
* Scores below `50` → `"Fail"`

---

In [13]:
scores = np.array([45, 72, 88, 39, 95, 60])
results = np.where(scores >= 50, "Pass", "Fail")
print(results)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass']


### Exercise 14 — Row and Column Operations

Given:

```python
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
```

Calculate:

1. Sum of every column
2. Sum of every row
3. Mean of every column
4. Mean of every row

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
rows, cols = np.shape(matrix)
for col in range(cols):
    sum_col = np.sum(matrix[:, col])
    print(f"Sum of column {col}: {sum_col}")
    
for row in range(rows):
    sum_row = np.sum(matrix[row, :])
    print(f"Sum of row {row}: {sum_row}")

for col in range(cols):
    mean_col = np.mean(matrix[:, col])
    print(f"Mean of column {col}: {mean_col}")

for row in range(rows):
    mean_row = np.mean(matrix[row, :])
    print(f"Mean of row {row}: {mean_row}")

### Exercise 15 — Find Maximum and Minimum Indices

Given:

```python
scores = np.array([72, 85, 91, 68, 95, 77])
```

Use NumPy functions to find:

* The maximum score
* The index of the maximum score
* The minimum score
* The index of the minimum score


In [19]:
scores = np.array([72, 85, 91, 68, 95, 77])
print(f"Maximum score: {np.max(scores)}")
print(f"The index of the maximum score: {np.argmax(scores)}")
print(f"The minimum score: {np.min(scores)}")
print(f"The index of the minimum score: {np.argmin(scores)}")

Maximum score: 95
The index of the maximum score: 4
The minimum score: 68
The index of the minimum score: 3


### Exercise 16 — Unique Values and Sorting

Given:

```python
arr = np.array([5, 3, 8, 3, 1, 5, 8, 2, 1, 9])
```

Find:

1. Unique values
2. Sorted values
3. Number of unique values

In [22]:
arr = np.array([5, 3, 8, 3, 1, 5, 8, 2, 1, 9])
print(f"Unique values: {np.unique(arr)}")
print(f"Sorted values: {np.sort(arr)}")
print(f"Number of unique values: {len(np.unique(arr))}")

Unique values: [1 2 3 5 8 9]
Sorted values: [1 1 2 3 3 5 5 8 8 9]
Number of unique values: 6


### Exercise 17 — Matrix Multiplication

Create the matrices:

```python
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
```

Calculate:

1. `A + B`
2. `A - B`
3. Element-wise multiplication `A * B`
4. Matrix multiplication `A @ B`

Explain the difference between `A * B` and `A @ B`.


In [24]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
print(f"A + B = {A + B}")
print(f"A - B = {A - B}")
print(f"A * B = {A*B}")
print(f"A @ B = {A@B}")

A + B = [[ 6  8]
 [10 12]]
A - B = [[-4 -4]
 [-4 -4]]
A * B = [[ 5 12]
 [21 32]]
A @ B = [[19 22]
 [43 50]]


### Exercise 18 — Random Dataset

Generate a NumPy array containing **100 random integers** between `1` and `100`.

Calculate:

* Mean
* Median
* Minimum
* Maximum
* Standard deviation

Then count how many values are greater than `50`.

In [27]:
arr = np.random.randint(low=1, high=100, size=100)
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Minimum: {np.min(arr)}")
print(f"Maximum: {np.max(arr)}")
print(f"Standar deviation: {np.round(np.std(arr), 2)}")

Mean: 49.64
Median: 49.0
Minimum: 6
Maximum: 96
Standar deviation: 26.65


### Exercise 19 — Normalize Data

Given:

```python
data = np.array([10, 20, 30, 40, 50])
```

Perform **Min-Max normalization** using:

```text
x_normalized = (x - min(x)) / (max(x) - min(x))
```

The resulting values should be between `0` and `1`.

In [31]:
def normalization(x: np.int64, min_value: np.int64, max_value: np.int64) -> np.float64:
    return (x - min_value)/(max_value - min_value)
data = np.array([10, 20, 30, 40, 50])
min_value = np.min(data)
max_value = np.max(data)
result = [normalization(x, min_value, max_value) for x in data]
print(result)

[0.0, 0.25, 0.5, 0.75, 1.0]


### Exercise 20 — Mini Data-Science Task

Given:

```python
students = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [95, 92, 88],
    [60, 68, 70],
    [85, 80, 84]
])
```

Each row represents a student and each column represents a subject.

Perform the following tasks:

1. Calculate the average score for each student.
2. Calculate the average score for each subject.
3. Find the student with the highest average.
4. Find the student with the lowest average.
5. Find the highest score in the entire dataset.
6. Find the lowest score in the entire dataset.
7. Count how many scores are greater than or equal to `80`.
8. Convert all scores to normalized values between `0` and `1`.

A possible solution should make extensive use of NumPy operations rather than Python `for` loops.

In [56]:
def avg_score_each_student(students: np.array)->list:
    results = []
    rows, _ = students.shape
    for row in range(rows):
        avg = np.round(np.mean(students[row, :]), 2)
        results.append(avg)
    return results

def avg_score_each_subject(students: np.array)->list:
    results = []
    _, cols = students.shape
    for col in range(cols):
        avg = np.round(np.mean(students[:, col]), 2)
        results.append(avg)
    return results
    
def max_avg_score_student(students: np.array) -> tuple:
    avg_scores = np.round(np.mean(students, axis=1), 2)
    idx = np.argmax(avg_scores)
    return (idx, avg_scores[idx])

def min_avg_score_student(students: np.array) -> tuple:
    avg_scores = np.round(np.mean(students, axis=1), 2)
    idx = np.argmin(avg_scores)
    return (idx, avg_scores[idx])

def max_score_dataset(students: np.array) -> tuple:
    row, col = np.unravel_index(np.argmax(students), students.shape)
    return ((row, col), students[row, col])

def min_score_dataset(students: np.array) -> tuple:
    row, col = np.unravel_index(np.argmin(students), students.shape)
    return ((row, col), students[row, col])

def count_score_greater_k(students: np.array, k: int) -> int:
    return len(students[students >= 80])

def normalization_students(students: np.array) -> np.array:
    min_value = np.min(students)
    max_value = np.max(students)

    return np.round(
        (students - min_value) / (max_value - min_value),
        2
    )
    
def main():
    students = np.array([
        [80, 75, 90],
        [65, 70, 72],
        [95, 92, 88],
        [60, 68, 70],
        [85, 80, 84]
    ])
    print(f"Calculate the average score for each student: {avg_score_each_student(students)}")
    print(f"Calculate the average score for each subject: {avg_score_each_subject(students)}")
    print(f"Find the student with highest average: {max_avg_score_student(students)}")
    print(f"Find the student with the lowest average: {min_avg_score_student(students)}")
    print(f"Find the highest score in the entire dataset: {max_score_dataset(students)}")
    print(f"Find the lowest score in the entire dataset {min_score_dataset(students)}")
    print(f"Count how many scores are greater than or equal to 80: {count_score_greater_k(students, k=80)}")
    print(f"Convert all scores to normalized values between 0 and 1: {nomalization_students(students)}")
if __name__ == "__main__":
    main()

Calculate the average score for each student: [81.67, 69.0, 91.67, 66.0, 83.0]
Calculate the average score for each subject: [77.0, 77.0, 80.8]
Find the student with highest average: (2, 91.67)
Find the student with the lowest average: (3, 66.0)
Find the highest score in the entire dataset: ((2, 0), 95)
Find the lowest score in the entire dataset ((3, 0), 60)
Count how many scores are greater than or equal to 80: 8
Convert all scores to normalized values between 0 and 1: [array([0.57, 0.43, 0.86]), array([0.14, 0.29, 0.34]), array([1.  , 0.91, 0.8 ]), array([0.  , 0.23, 0.29]), array([0.71, 0.57, 0.69])]
